development:
  adapter: mysql
  encoding: utf8
  database: draftback_development
  username: draftback
  password: draftback
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: draftback_production
  username: draftback
  password: draftback
  host: localhost
